#pragma once

enum AVIErrors
{
	AVIE_NOERROR,

	AVIE_FILE_OPEN_READ_ERROR,
	AVIE_FILE_OPEN_WRITE_ERROR,
	AVIE_FILE_READ_ERROR,
	AVIE_FILE_WRITE_ERROR,

	AVIE_BAD_RIFF_CODE,
	AVIE_BAD_AVI_CODE,
	AVIE_COPYRIGHTED,
	AVIE_STREAM_HEADER_NOT_MJPG,
	AVIE_STREAM_FORMAT_NOT_MJPG,
	AVIE_STREAM_FORMAT_NOT_24BIT,

	AVIE_STRH_OUTSIDE_STRL,
	AVIE_STRF_OUTSIDE_STRL,
	AVIE_STRD_OUTSIDE_STRL,
	AVIE_STRN_OUTSIDE_STRL,
	AVIE_STRF_BEFORE_STRH,

	AVIE_MOVI_BEFORE_STRL,
	AVIE_REC_OUTSIDE_MOVI,
	AVIE_IDX1_BEFORE_MOVI,
	AVIE_STREAMCHUNK_OUTSIDE_MOVI_OR_REC,
};

extern volatile int avi_error;
extern volatile unsigned int error_data;
